#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     armMotor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    gripperServo,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    faceServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
void robotControl()
{
	float speed;
	float factor;
	int servo1pos;
	bool faceDir = true;
	while(true)
	{
		faceDir = faceDir;
		getJoystickSettings(joystick);  // Update Buttons and Joysticks
		if( joy1Btn(3) )//This provides a speed toggle,
		{
			speed = !speed;
			wait1Msec(10);
		}
		if(speed)
		{
			factor = 1.81429;
		}
		else
		{
			factor = 5.00; //Slows the driving down to a reasonable amount.
		}

		motor[armMotor] = joystick.joy2_y1/5;
		motor[rightMotor] = joystick.joy1_y1/factor;
		motor[leftMotor] = joystick.joy1_y2/factor;

		/*Servo Section*/

		if((joy2Btn(1))) servo1pos += 2;
		else if((joy2Btn(2))) servo1pos -= 2;
		servo[servo1] = servo1pos;
		wait1Msec(20);

		if(faceDir)  servo[faceServo] = 240;
		if(!faceDir)  servo[faceServo] = 10;

		/*Noises*/

		int min = 1000;
	  int max = 6000;

    PlayTone((rand() % (max-min)) + min, 5);     //rand() % (max-min)) + min;
	}
}
task main()
{
	robotControl();
}
