#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor2,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
* Show the arc distance traveled "s"
* s = theta*radius
*/

const unsigned byte radiusIn = 2;
const float radiusM = 5.08;

float s;
float angle;

task main()
{
	nMotorEncoder[motor1] = 0;     //AndyMark: 1120 ticks/rev
	while (true) {
		angle = nMotorEncoder[motor1] * (360 / 1120);
		s = angle * radiusM;
		nxtDisplayCenteredBigTextLine(2, "%f", angle);
		nxtDisplayCenteredBigTextLine(4, "%f", s);

		while(nNxtButtonPressed == 1) {
			motor[motor1] = 100;
			motor[motor2] = -100;
			angle = nMotorEncoder[motor1] * (360 / 1120);
			s = angle * radiusM;
			nxtDisplayCenteredBigTextLine(2, "%f", angle);
			nxtDisplayCenteredBigTextLine(4, "%f", s);
		}
		while(nNxtButtonPressed == 2) {
			motor[motor1] = -100;
			motor[motor2] = 100;
			angle = nMotorEncoder[motor1] * (360 / 1120);
			s = angle * radiusM;
			nxtDisplayCenteredBigTextLine(2, "%f", angle);
			nxtDisplayCenteredBigTextLine(4, "%f", s);
		}
	}
}
