#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     motor2,        tmotorTetrix, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//about 320 ticks per revolution

task DriveMotors();

task main()
{
	nMotorEncoder[motor1] = 0;
	nMotorEncoder[motor2] = 0;

	long encTemp1, encTemp2, diff1, diff2;
	int rate1, rate2;

	int sampleMillis = 225;

	startTask(DriveMotors);

	while (true) {
		//getJoystickSettings(joystick);
		//motor[motor1] = (int)(joystick.joy1_y1 / 1.27);
		//motor[motor2] = (int)(joystick.joy1_y1 / 1.27);
		time1[T1] = 0;
		encTemp1 = nMotorEncoder[motor1];
		encTemp2 = nMotorEncoder[motor2];
		while (time1[T1] < sampleMillis) {
			;;
		}
		diff1 = nMotorEncoder[motor1] - encTemp1;
		diff2 = nMotorEncoder[motor2] - encTemp2;
		rate1 = (int)(diff1 / (sampleMillis * pow(10, -3)));      //units: encoder counts / sec
		rate2 = (int)(diff2 / (sampleMillis * pow(10, -3)));
		//nxtDisplayCenteredBigTextLine(2, "%d", rate1);
		//nxtDisplayCenteredBigTextLine(4, "%d", rate2);
		//nxtDisplayCenteredBigTextLine(4, "%d", rate1 - rate2);
		writeDebugStreamLine("%d", rate1 - rate2);
		nxtDisplayCenteredBigTextLine(2, "%d", nMotorEncoder[motor1] - nMotorEncoder[motor2]);
		//nxtDisplayCenteredBigTextLine(4, "%d", nMotorEncoder[motor2]);
	}
}

task DriveMotors()
{
	while (true) {
		getJoystickSettings(joystick);
		motor[motor1] = /*(int)(joystick.joy1_y1 / 1.27)*/100;
		motor[motor2] = /*(int)(joystick.joy1_y1 / 1.27)*/100;
		delay(1);
	}
}
