#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IRR,            sensorI2CCustom)
#pragma config(Sensor, S4,     IRL,            sensorI2CCustom)
#pragma config(Motor,  motorA,          magLeft,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          magRight,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor2,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int e;

task main()
{
	eraseDisplay();
	getJoystickSettings(joystick);
	nMotorEncoder[motor2] = 0;
	while(true)
	{
		bFloatDuringInactiveMotorPWM = true;
		e = nMotorEncoder[motor2];
		nxtDisplayCenteredBigTextLine(4, "%d", e);
		//bFloatDuringInactiveMotorPWM = false;

		motor[motor2] = joystick.joy1_y2 / 1.27;
	}
}
