#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C3_1,     roller,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     chassisR,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     chassisL,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     liftL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorI,        tmotorNXT, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    trailerServoL,        tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    trailerServoR,        tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    gateServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    bucketServoL,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    bucketServoR,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

static float fullFactor = 0.781;
static float halfFactor = 0.391;

task main()
{
	while (true) {
		getJoystickSettings(joystick);
		motor[roller] = joystick.joy1_y1 * halfFactor;
	}
}
