#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     chassisL,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     chassisR,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     scissorL,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     scissorR,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     bucketL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     bucketR,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    trailerServo,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    gateServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    bucketServoL,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    bucketServoR,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	eraseDisplay();
	nMotorEncoder[scissorL] = 0;
	nMotorEncoder[scissorR] = 0;

	while(true)
	{
		//nMotorEncoder[scissorL] = 0;
		//nMotorEncoder[scissorR] = 0;
		nxtDisplayCenteredBigTextLine(4, "%d", nMotorEncoder[scissorL]);
		while(nNxtButtonPressed == 1)
		{
			motor[scissorL] = 100;
			motor[scissorR] = -100;
			nxtDisplayCenteredBigTextLine(4, "%d", nMotorEncoder[scissorL]);
		}
		while(nNxtButtonPressed == 2)
		{
			motor[scissorL] = -100;
			motor[scissorR] = 100;
			nxtDisplayCenteredBigTextLine(4, "%d", nMotorEncoder[scissorL]);
		}
		motor[scissorL] = 0;
		motor[scissorR] = 0;
	}
}
