#pragma config(Sensor, S1,     HTSPB,                sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*   HiTechnic Experimenter's Kit for the SuperPro

Experiment - 9 Speaker

This program  first plays a sequence of three ascending
notes using just O0 and then three pairs of descending
notes using both O0 and O1.

*/

// One octive of note frequencies
#define  TONE_C4   262 - 100
#define  TONE_CS4   277 - 100
#define  TONE_D4   294 - 100
#define  TONE_DS4   311 - 100
#define  TONE_E4   330 - 100
#define  TONE_F4   349 - 100
#define  TONE_FS4   370 - 100
#define  TONE_G4   392 - 100
#define  TONE_GS4   415 - 100
#define  TONE_A4   440 - 100
#define  TONE_AS4   466 - 100
#define  TONE_B4   494 - 100
#define  TONE_C5   523 - 100
#define SOOPRLOW 30


#include "hitechnic-superpro.h"

task main() {
	HTSPBsetupIO(HTSPB, 0x10);
	while(true)
	{

		/*HTSPBwriteAnalog(HTSPB, HTSPB_DACO0, DAC_MODE_SQUAREWAVE, TONE_C4, 1023);
		wait1Msec(200);
		HTSPBwriteAnalog(HTSPB, HTSPB_DACO0, DAC_MODE_SQUAREWAVE, TONE_DS4, 1023);
		wait1Msec(400);
		HTSPBwriteAnalog(HTSPB, HTSPB_DACO0, DAC_MODE_SQUAREWAVE, SOOPRLOW, 1023);
		wait1Msec(200);
		HTSPBwriteAnalog(HTSPB, HTSPB_DACO0, DAC_MODE_SQUAREWAVE, 1, 0);
		wait1Msec(200);

		HTSPBwriteAnalog(HTSPB, HTSPB_DACO0, DAC_MODE_SQUAREWAVE, TONE_F4, 1023);
		HTSPBwriteAnalog(HTSPB, HTSPB_DACO1, DAC_MODE_SQUAREWAVE, TONE_G4, 1023);
		wait1Msec(200);
		HTSPBwriteAnalog(HTSPB, HTSPB_DACO0, DAC_MODE_SQUAREWAVE, TONE_E4, 1023);
		HTSPBwriteAnalog(HTSPB, HTSPB_DACO1, DAC_MODE_SQUAREWAVE, TONE_CS4, 1023);
		wait1Msec(200);
		HTSPBwriteAnalog(HTSPB, HTSPB_DACO0, DAC_MODE_SQUAREWAVE, TONE_C4, 1023);
		HTSPBwriteAnalog(HTSPB, HTSPB_DACO1, DAC_MODE_SQUAREWAVE, TONE_B4, 1023);
		wait1Msec(400);
		HTSPBwriteAnalog(HTSPB, HTSPB_DACO0, DAC_MODE_SQUAREWAVE, 1, 0);
		HTSPBwriteAnalog(HTSPB, HTSPB_DACO1, DAC_MODE_SQUAREWAVE, 1, 0);*/

		int i;

		for(int i = 0; i < 200; i++)
		{
			HTSPBwriteAnalog(HTSPB, HTSPB_DACO0, DAC_MODE_SQUAREWAVE, i, 1023);
			wait1Msec(50);
		}

		wait1Msec(50);

		for(int k = 200; k > 0; k--)
		{
			HTSPBwriteAnalog(HTSPB, HTSPB_DACO0, DAC_MODE_SQUAREWAVE, k, 1023);
			wait1Msec(50);
		}

	}

}
