#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    cont1,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "..\Driver Suite\drivers\hitechnic-sensormux.h"
#include "hitechnic-accelerometer.h"

const tMUXSensor accel = msensor_S3_3;

int readAvgXaxis();
int readAvgYaxis();

int x, y;

int _x_axis, _y_axis, _z_axis;
int avgDelay = 1;
int numAvg = 15;

task main()
{
	while(true)
	{
		nxtDisplayCenteredBigTextLine(4, "%d", readAvgYaxis());
		//servo[cont1] = 127;
		x = readAvgXaxis();
		y = readAvgYaxis();
	}
}

int readAvgXaxis()                                   //eliminates noise of readings
{
	int avgX;
	for(int i = 0; i < numAvg; i++)
	{
		// Read all of the axes at once
		if (!HTACreadAllAxes(accel, _x_axis, _y_axis, _z_axis))
		{
			nxtDisplayTextLine(4, "ERROR!!");
			wait1Msec(avgDelay);
			//StopAllTasks();
		}
		avgX = (avgX + _x_axis) / 2;       //rolling average of x
	}
	return(avgX*.4444 + 100);
}

int readAvgYaxis()                                   //eliminates noise of readings
{
	int avgY;
	for(int i = 0; i < numAvg; i++)
	{
		// Read all of the axes at once
		if (!HTACreadAllAxes(accel, _x_axis, _y_axis, _z_axis))
		{
			nxtDisplayTextLine(4, "ERROR!!");
			wait1Msec(avgDelay);
			//StopAllTasks();
		}
		avgY = (avgY + _y_axis) / 2;       //rolling average of x
	}
	return(abs(avgY*.4444-180));
}
