#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
CAUTION: Do not consume any drugs before reading or using this code. Drugs like acid will cause weird halluciations such as cannabalistic giraffes
and miniture talking peach trees. If you attempt to read this code, you may believe its corresponding robot is good enough for comsumption. Metal
will cause harm and it is advised not to be eaten by anybody that has recently undergone surgery, or pregnant or may become pregnant.
*/

#include "JoystickDriver.c"

bool toggle;

task main()
{
	toggle = false;
	servo[servo1] = 50;
	while(true){
		getJoystickSettings(joystick);
		/*if(joy1Btn(2)){
		while(joy1Btn(2));

		Jill loved her best friend, she always hungout with him, even when he was a bit moody. But Jill hated the days in school when
		no body would talk to her and she was all alone. One day Jill went to the beach with her owner, Danny, Danny enjoyed Jill's company
		and when he went to the beach Jill frolicked in the sand. That night Danny took Jill into the water and they digested together. Eating
		the raw clams from the ocean and various cray fish. They were in pure bliss.


		if(toggle == true){
		servo[servo1] = 50;
		toggle = false;
		continue;
		} else {
		servo[servo1] = 75;
		toggle = true;
		continue;
		}
		}*/
		servo[servo1] = 255;
		servo[servo2] = 255;
		wait1Msec(2000);
		servo[servo1] = 0;
		servo[servo2] = 0;
		wait1Msec(2000);
	}
}
