#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     HTAC,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



//NOT WORKING CODE, NEED TO FIX STRUCT PROBLEMS
#include "hitechnic-accelerometer.h"

int readAxis(int avg);  																	//accel function   rolling average function of x
void forward(int p, float t);

typedef struct{
	int x;
	int y;
	int z;
}axis;

task main()
{
	//axis a;
	eraseDisplay();
	while(true)
	{
	 // a.x = 8;
	 // a.y = 9;
	 // a.z = 10;
	 axis a;
	 a = readAxis(10);

		nxtDisplayCenteredBigTextLine(1,"X=%3d",a.x);
		nxtDisplayCenteredBigTextLine(3,"Y=%3d",a.y);
		nxtDisplayCenteredBigTextLine(5,"Z=%3d",a.z);
		wait10Msec(10);
		//	if(avgX < 80)
		//		forward(30,1);
	}

}



void readAxis(int avg, int &b )
{
	//nt avgX;
	for(int i = 0; i < avg; i++)
	{
		if (!HTACreadAllAxes(HTAC, b.x, b.y, b.z)) {
			nxtDisplayTextLine(4, "ERROR!!");
			StopAllTasks();
		}
b.y = 10;
b.z = 5;

	}
	return(b);
}

void forward(int p, float t)
{
	motor[rightMotor] = p;
	motor[leftMotor] = -p;
	wait1Msec(t);
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}
