#pragma config(Motor,  motorA,          mag1,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mag2,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  motor[mag1] = 100;
  motor[mag2] = 100;
  wait1Msec(10000);
}
