#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IRL,            sensorI2CCustom)
#pragma config(Sensor, S4,     IRR,            sensorI2CCustom)
#pragma config(Motor,  motorA,          motor1,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     backLeftMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontLeftMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     backRightMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     frontRightMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     M4Motor,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     LBoomMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     RBoomMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    camServo1,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    camServo2,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

//float factor = .63;
//float factor = .1969;
float factor = 1.27;

int e;

task OpenGate();

task main()
{
	nMotorEncoder[motor1] = 0;
	while(true)
	{
		motor[M4Motor] = joystick.joy1_y1 / 1.28;
		getJoystickSettings(joystick);
		if(nMotorEncoder[motor1] > 180 || nMotorEncoder[motor1] < -180) nMotorEncoder[motor1] = 0;
		//e = nMotorEncoder[motor1];
		//e = nMotorEncoder[motor1];
		nxtDisplayCenteredBigTextLine(4, "%d", nMotorEncoder[motor1]);
		if(/*joystick.joy1_y1 > 1*/ nNxtButtonPressed == 3)
			StartTask(OpenGate, 7);
		while(joy1Btn(1))
		{
			motor[motor1] = joystick.joy1_y1 / 1.27;
			nxtDisplayCenteredBigTextLine(4, "%d", nMotorEncoder[motor1]);
			if(nMotorEncoder[motor1] > 180 || nMotorEncoder[motor1] < -180) nMotorEncoder[motor1] = 0;
		}
	}
}

task OpenGate()
{
	eraseDisplay();
	//nMotorEncoder[motor1] = e;
	getJoystickSettings(joystick);
	while(true)
	{
		if(nMotorEncoder[motor1] > 180 || nMotorEncoder[motor1] < -180) nMotorEncoder[motor1] = 0;
		bFloatDuringInactiveMotorPWM = false;
		nxtDisplayCenteredBigTextLine(4, "%d", nMotorEncoder[motor1]);

		//if(/*joystick.joy1_y1 > 1*/ nNxtButtonPressed == 3)
		//{
		if(nMotorEncoder[motor1] > 30)
		{
			motor[motor1] = -20;
		}
		else if(nMotorEncoder[motor1] < -30)
		{
			motor[motor1] = 20;
		}
		else
		{
			motor[motor1] = 0;
		}
		//}
		//motor[M4Motor] = joystick.joy1_y1 / factor;
		//motor[LBoomMotor] = joystick.joy1_y1 / factor;
		//motor[RBoomMotor] = joystick.joy1_y1 / factor;
		//writeDebugStreamLine("%f", joystick.joy1_y1 / factor);
		//motor[RBoomMotor] = joystick.joy1_y2 / factor;
		//writeDebugStreamLine("%f", joystick.joy1_y2 / factor);
	}
	/*motor[LBoomMotor] = 80;
	motor[RBoomMotor] = 80;
	wait1Msec(500);
	motor[LBoomMotor] = 0;
	motor[RBoomMotor] = 0;*/
}
