#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     accel,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    cont1,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    bumpServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-accelerometer.h"

int readAvgXaxis();
int readAvgYaxis();
void moveToAngle(int a);

int _x_axis, _y_axis, _z_axis;
int avgDelay = 1;
int numAvg = 15;

int bumpServoPos;

task main()
{
	bumpServoPos = 135;
	//while(true);
	moveToAngle(160);
	servo[bumpServo] = bumpServoPos;
}

int readAvgXaxis()                                   //eliminates noise of readings
{
	int avgX;
	for(int i = 0; i < numAvg; i++)
	{
		// Read all of the axes at once
		if (!HTACreadAllAxes(accel, _x_axis, _y_axis, _z_axis))
		{
			nxtDisplayTextLine(4, "ERROR!!");
			wait1Msec(avgDelay);
			//StopAllTasks();
		}
		avgX = (avgX + _x_axis) / 2;       //rolling average of x
	}
	return(avgX*.4444 + 100);
}

int readAvgYaxis()                                   //eliminates noise of readings
{
	int avgY;
	for(int i = 0; i < numAvg; i++)
	{
		// Read all of the axes at once
		if (!HTACreadAllAxes(accel, _x_axis, _y_axis, _z_axis))
		{
			nxtDisplayTextLine(4, "ERROR!!");
			wait1Msec(avgDelay);
			//StopAllTasks();
		}
		avgY = (avgY + _y_axis) / 2;       //rolling average of x
	}
	return(abs(avgY*.4444-180));
}

void moveToAngle(int a)
{
	if(readAvgYaxis() < a)
		while(readAvgYaxis() < a)
			servo[cont1] = 0;
	else
		while(readAvgYaxis() > a)
			servo[cont1] = 255;
}
