#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     HTAC,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-accelerometer.h"

int readAxis(int avg)
{
	int avgX = 0;
	int _x_axis, _y_axis, _z_axis;
	for(int i = 0; i < avg; i++)
	{
		if (!HTACreadAllAxes(HTAC, _x_axis, _y_axis, _z_axis))
		{
			nxtDisplayTextLine(4, "ERROR!!");
			wait1Msec(1000);
			StopAllTasks();
		}
		avgX += _x_axis;
	}
	return(avgX/avg);
}

task main()
{
	eraseDisplay();
	while(true)
	{
		int x = readAxis(30) *0.4444 + 100;
		nxtDisplayCenteredBigTextLine(1,"X=%3d",x);
		wait10Msec(10);

	}

}
