#pragma config(Sensor, S3,     IRL,            sensorI2CCustom)
#pragma config(Sensor, S2,     IRR,            sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "..\Driver Suite\drivers\hitechnic-irseeker-v2.h"

void updateSensors();

static int _dirACL;
static int _dirACR;
static int acS1L, acS2L, acS3L, acS4L, acS5L;
static int acS1R, acS2R, acS3R, acS4R, acS5R;

task main()
{
	while(true){
		updateSensors();
		nxtDisplayCenteredBigTextLine(3, "%d", _dirACL);
		nxtDisplayCenteredBigTextLine(6, "%d", _dirACR);
	}
}

static void updateSensors()
{
	//HTIRS2setDSPMode(IRL, _mode);
	//HTIRS2setDSPMode(IRR, _mode);

	_dirACL = HTIRS2readACDir(IRL);
	_dirACR = HTIRS2readACDir(IRR);

	HTIRS2readAllACStrength(IRL,  acS1L,  acS2L,  acS3L,  acS4L,  acS5L);
	HTIRS2readAllACStrength(IRR,  acS1R,  acS2R,  acS3R,  acS4R,  acS5R);
}
