#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     HTAC,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-accelerometer.h"

int readAxis(int avg)
{
	int avgX = 0;
	int _x_axis, _y_axis, _z_axis;
	for(int i = 0; i < avg; i++)
	{
		if (!HTACreadAllAxes(HTAC, _x_axis, _y_axis, _z_axis))
		{
			nxtDisplayTextLine(4, "ERROR!!");
			wait1Msec(1000);
			StopAllTasks();
		}
		avgX += _x_axis;
	}
	return(avgX/avg*0.44444+100);
}

void go(int l, int r, float t)
{
	motor[rightMotor] = l;
	motor[leftMotor] = -r;
	wait1Msec(t);

}

//eraseDisplay();
//nxtDisplayCenteredBigTextLine(1,"X=%3d",x);

task main()
{
	int x;
	go(10,10,8000);		//Go go
	do
	{
		x = readAxis(30);
		go(20,20,200);
	}while(x < 85);					//Continue untill at bottom of ramp

	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
  wait1Msec(1000);
  go(20,20,1500);

  PlaySound(soundBeepBeep);
  go(-25,25,900);			//Turn towards feild

  wait1Msec(1000);
  PlaySound(soundBeepBeep);
  go(100,100,900);			//Ram into pole

  go(40,-40,900);
  go(100,100,1000);
  wait1Msec(1000);
  PlaySound(soundBeepBeep);

  go(50,-50,1000);
  go(100,100,1000);
}
