#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    gripper,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int servoPos = 127;
	while(true)
	{
		if(nNxtButtonPressed == 1)
		{
			servoPos--;
			wait1Msec(10);
		}
		else if(nNxtButtonPressed == 2)
		{
			servoPos++;
			wait1Msec(10);
		}
		servo[gripper] = servoPos;
		nxtDisplayCenteredBigTextLine(4, "%d", servoPos);
	}
}
