#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     loaderMotorL,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     loaderMotorR,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    loaderServoL,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    loaderServoR,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task driveServos;
void initServos(int *LSLPos, int *LSRPos);

int loaderServoLPos;
int loaderServoRPos;

task main(){
	float limitingFactor = 0.781;
	initServos(&loaderServoLPos, &loaderServoRPos);
	servo[loaderServoL] = loaderServoLPos;
	servo[loaderServoR] = loaderServoRPos;
	StartTask(driveServos);
	while(true){
		getJoystickSettings(joystick);
		motor[loaderMotorL] = joystick.joy1_y2 * limitingFactor;
		motor[loaderMotorR] = -joystick.joy1_y2 * limitingFactor;

		wait1Msec(10);
	}
}

//init servo positions
void initServos(int *LSLPos, int *LSRPos){
	*LSLPos = 170;
	*LSRPos = 85;
}

task driveServos{
	bool presetToggle = false;
	while(true){
		if(joy1Btn(6) && loaderServoLPos > 0 && loaderServoRPos < 255){
			loaderServoLPos -= 5;
			loaderServoRPos += 5;
		}
		if(joy1Btn(5) && loaderServoLPos < 255 && loaderServoRPos > 0){
			loaderServoLPos += 5;
			loaderServoRPos -= 5;
		}
		if(joy1Btn(11)){
			while(joy1Btn(11));
			if(presetToggle == false){
				presetToggle = true;
				loaderServoLPos = 170;
				loaderServoRPos = 85;
				PlaySound(soundBeepBeep);
				continue;
			}
			if(presetToggle == true){
				presetToggle = false;
				loaderServoLPos = 120;
				loaderServoRPos = 135;
				PlaySound(soundBlip);
				continue;
			}
		}
		servo[loaderServoL] = loaderServoLPos;
		servo[loaderServoR] = loaderServoRPos;
		wait1Msec(10);
	}
}
