#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     chassisL,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     chassisR,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     liftL,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     liftR,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     bucketL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     bucketR,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    trailerServo,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    gateServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    bucketServoL,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    bucketServoR,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task liftPresets();

void init();
void driveChassis(bool t);

static float fullFactor = 0.781;
static float halfFactor = 0.391;

task main() {
	bool chassisToggle = false;
	init();
	startTask(liftPresets);
	while (true) {
		getJoystickSettings(joystick);
		if (joy1Btn(2)) {
			wait1Msec(200);
			chassisToggle = !chassisToggle;
			playImmediateTone((rand() % (800-300)) + 300, 5);
		}
		driveChassis(chassisToggle);

		delay(1);
	}
}

void init() {
	nMotorEncoder[liftL] = 0;
	nMotorEncoder[liftR] = 0;
	nMotorEncoder[chassisL] = 0;
	nMotorEncoder[chassisR] = 0;
}

void driveChassis(bool t)
{
	if (t) {
		motor[chassisL] = joystick.joy1_y1 * fullFactor;
		motor[chassisR] = -joystick.joy1_y2 * fullFactor;
		} else {
		motor[chassisL] = joystick.joy1_y1 * halfFactor;
		motor[chassisR] = -joystick.joy1_y2 * halfFactor;
	}
}

task liftPresets() {
	while (true) {
		getJoystickSettings(joystick);
		//highest setting
		if (joy2Btn(3) && nMotorEncoder[liftL] > -5500) {
			while (nMotorEncoder[liftL] > -5500) {
				motor[liftL] = -100;
				motor[liftR] = -100;
			}
		}
		// medium-high setting
		if (joy2Btn(4) && nMotorEncoder[liftL] > -4000) {
			while (nMotorEncoder[liftL] > -4000) {
				motor[liftL] = -100;
				motor[liftR] = -100;
			}
		} else if (joy2Btn(4)) {
			while (nMotorEncoder[liftL] < -4000) {
				motor[liftL] = 25;
				motor[liftR] = 25;
			}
		}
		// medium-low setting
		if (joy2Btn(1) && nMotorEncoder[liftL] > -3000) {
			while (nMotorEncoder[liftL] > -3000) {
				motor[liftL] = -100;
				motor[liftR] = -100;
			}
		} else if (joy2Btn(1)) {
			while (nMotorEncoder[liftL] < -3000) {
				motor[liftL] = 25;
				motor[liftR] = 25;
			}
		}
		// low setting
		if (joy2Btn(2) && nMotorEncoder[liftL] > -1500) {
			while (nMotorEncoder[liftL] > -1500) {
				motor[liftL] = -100;
				motor[liftR] = -100;
			}
		} else if (joy2Btn(2)) {
			while (nMotorEncoder[liftL] < -1500) {
				motor[liftL] = 25;
				motor[liftR] = 25;
			}
		}
		// ground setting
		if (joystick.joy2_TopHat == 0) {
			while (nMotorEncoder[liftL] < 0) {
				motor[liftL] = 25;
				motor[liftR] = 25;
			}
		}
		delay(1);
	}
}
