#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRR,            sensorI2CCustom)
#pragma config(Sensor, S3,     IRL,            sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "..\Driver Suite\drivers\hitechnic-irseeker-v2.h"

void updateSensors();

static int _dirACL;
static int _dirACR;
static int acS1L, acS2L, acS3L, acS4L, acS5L;
static int acS1R, acS2R, acS3R, acS4R, acS5R;

task main()
{
	while(true){
		updateSensors();
		nxtDisplayCenteredBigTextLine(3, "%d", _dirACL);
		nxtDisplayCenteredBigTextLine(6, "%d", _dirACR);
		//nxtDisplayCenteredBigTextLine(3, "%d", (_dirACL + _dirACR)/2);

	}
}

static void updateSensors()
{
	//HTIRS2setDSPMode(IRL, _mode);
	//HTIRS2setDSPMode(IRR, _mode);

	_dirACL = HTIRS2readACDir(IRL);
	_dirACR = HTIRS2readACDir(IRR);

	HTIRS2readAllACStrength(IRL,  acS1L,  acS2L,  acS3L,  acS4L,  acS5L);
	HTIRS2readAllACStrength(IRR,  acS1R,  acS2R,  acS3R,  acS4R,  acS5R);
}
